### PR TITLE
Fix: Ball position in RTL layout

### LINKED ISSUE #11: Ball position is wrong in RTL apps
Hello again,

Unfortunately we have an issue with the ball position while the app is RTL with AnimatedTabBar.

Simulator Screenshot - iPhone 15 Pro Max - 2024-07-23 at 16 38 34

### PR DESCRIPTION
**Pull request by amirsaam**
Fixes #11

### CODE REVIEW

File: Sources/AnimatedTabBar/AnimatedTabbar.swift [hunk 1]
```diff
@@ -63,11 +63,19 @@ public struct AnimatedTabBar: View {
...
             HStack(alignment: .bottom) {
-                circle
-                Spacer()
+                if layoutDirection == .rightToLeft {
+                    Spacer()
+                    circle
+                        .scaleEffect(x: layoutDirection == .rightToLeft ? -1 : 1, y: 1)
+                } else {
+                    circle
+                    Spacer()
```
Comment (f3dm76) [inline Sources/AnimatedTabBar/AnimatedTabbar.swift:77]: Are you sure you don't need the scaleEffect?

Comment (amirsaam) [reply Sources/AnimatedTabBar/AnimatedTabbar.swift:77]: Am I sure that I don't need? 😬
You can test it, the spacer alone won't fix it

**Comment by amirsaam** [comment]
@f3dm76 any update? my prs are not reviewed after your comments.
